spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/foodies}

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY:}
aws.secret.key=${AWS_SECRET_KEY:}
aws.region=${AWS_REGION:ap-south-1}
aws.s3.bucketname=${AWS_S3_BUCKETNAME:}

jwt.secret.key=${JWT_SECRET_KEY:a-string-secret-at-least-256-bits-long}

#razorpay configuration
razorpay_key=${RAZORPAY_KEY:}
razorpay_secret=${RAZORPAY_SECRET:}